---
title: "React Notes Stateless"
type: "challenge"
description: "Render a static Notes application using React stateless components"
tags: "javascript, react, stateless components"
ignore:
- "node_modules/"
- "react-notes-stateless.md"
